matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
script:
  - brew install angular-cli && \
  - npm ci
  - npm run build:prod:all
  - npm run package:mac
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

